### <----------------------------------------> GIT HUB ACTIONS - FOR TEST EXECUTION <----------------------------------------> ###

name: Test Execution

# start job on all push #
on:
    push:
        branches:
            - master

# set the job for executing tests #        
jobs:
    API-test:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
            - name: Clone the Repository
              uses: actions/checkout@v2
            - name: Install node
              uses: actions/setup-node@v1
            - name: print secrets
              run: |
                echo $FR_TEST_TOKEN >> ./.env
                cat src/.env
              shell: bash
              env:
                FR_TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
            - name: Install Dependencies
              run: npm ci
            - name: Run Tests
              run: npm test
            - name: Print Run id
              run: echo $GITHUB_RUN_ID
              env:
                GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
                FR_USERNAME: ${{ secrets.USERNAME }}
                FR_PASSWORD: ${{ secrets.PASSWORD }}
                FR_TEST_TOKEN: ${{ secrets.TEST_TOKEN }}

