### <----------------------------------------> GIT HUB ACTIONS <----------------------------------------> ###

name: Frisby CI

# start job on all push #
on:
    push:
        branches:
            - master

# set the job for executing tests #        
jobs:
    API-test:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
            - name: Clone the Repository
              uses: actions/checkout@v2
            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                java-version: 11
            - name: Run tests
              run: jest
            - name: Print Run id
              run: echo $GITHUB_RUN_ID
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

