### <----------------------------------------> GIT HUB ACTIONS <----------------------------------------> ###

name: Code Quality Scan

# start job on all push #
on:
    push:
        branches:
            - master

# set the job #        
jobs:
    sonarcloudTrigger:
        name: SonarCloud Trigger
        runs-on: ubuntu-latest
        steps:
            - name: Clone the Repository
              uses: actions/checkout@v2
            - name: Analyze with SonarCloud
              uses: sonarsource/sonarcloud-github-action@master
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}