### <----------------------------------------> GIT HUB ACTIONS - FOR SONAR CUBE <----------------------------------------> ###

name: Sonar Code Quality Scan

# start job on all push #
on:
    push:
        branches:
            - master

# set the job for sonar code scan #        
jobs:
    sonarcloudTrigger:
        name: Sonar Code Quality Scan
        runs-on: ubuntu-latest
        steps:
            - name: Clone the Repository
              uses: actions/checkout@v2
              with:
                # Disabling shallow clone is recommended for improving relevancy of reporting
                fetch-depth: 0
            - name: Code Analysis with Sonar
              uses: sonarsource/sonarcloud-github-action@master
              with:
                args: >
                  -Dsonar.organization=msharma-tw_frisby-test-framework
                  -Dsonar.projectKey=msharma-tw
              env:
                GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}